kind: pipeline
name: zbxtable
steps:
  - name: build
    image: canhgia809/go:1.21.4-upx
    commands:
      - wget -q -c https://dl.cactifans.com/stable/zbxtable/web-latest.tar.gz && tar xf web-latest.tar.gz
      - go install github.com/go-bindata/go-bindata/go-bindata@latest
      - chmod a+x ./control
      - ./control build
      - mv zbxtable zbxtable-`git describe --tags`
      - upx -9 -o zbxtable zbxtable-`git describe --tags`
      - ./control pack
  - name: scp dev
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: 222_host
      port:
        from_secret: port
      username:
        from_secret: username
      password:
        from_secret: 222_password
      command_timeout: 10m
      target:
        - /home/wwwroot/downloads/dev
      source:
        - ./*.tar.gz
    when:
      branch:
        - dev
  - name: scp prod
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: 222_host
      port:
        from_secret: port
      username:
        from_secret: username
      password:
        from_secret: 222_password
      command_timeout: 10m
      target:
        - /home/wwwroot/downloads/stable
      source:
        - ./*.tar.gz
    when:
      branch:
        - 2.1
  - name: scp demo
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: demo_host
      port:
        from_secret: demo_port
      username:
        from_secret: demo_username
      password:
        from_secret: demo_password
      command_timeout: 10m
      target:
        - /tmp/zbxtable
      source:
        - zbxtable
      rm: true
    when:
      branch:
        - demo
  - name: ssh restart
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: demo_host
      username:
        from_secret: demo_username
      password:
        from_secret: demo_password
      port:
        from_secret: demo_port
      command_timeout: 10m
      script:
        - systemctl stop zbxtable
        - rm -rf /usr/local/zbxtable/zbxtable
        - mv /tmp/zbxtable/zbxtable /usr/local/zbxtable/
        - systemctl start zbxtable
    when:
      branch:
        - demo