package model

import "time"

type Topology struct {
	ID              int       `gorm:"column:id;primaryKey;autoIncrement" json:"id"`
	Nodes           string    `gorm:"column:nodes;type:text" json:"nodes"`
	Edges           string    `gorm:"column:edges;type:text" json:"edges"`
	Topology        string    `gorm:"column:topology;size:200" json:"topology"`
	Status          string    `gorm:"column:status;size:10" json:"status"`
	ZID             int       `gorm:"column:zid;default:0" json:"zid"`                           // Zabbix实例主键ID，0表示未指定
	BackgroundImage string    `gorm:"column:background_image;type:text" json:"background_image"` // 背景图片文件路径
	CanvasWidth     int       `gorm:"column:canvas_width;default:3000" json:"canvas_width"`      // 画布宽度
	CanvasHeight    int       `gorm:"column:canvas_height;default:2000" json:"canvas_height"`    // 画布高度
	CreatedAt       time.Time `gorm:"column:created_at;autoCreateTime" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;autoUpdateTime" json:"updated_at"`
}

// TableName Topology
func (t *Topology) TableName() string {
	return TableName("topology")
}

// TopologyList struct
type TopologyList struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    struct {
		Items []Topology `json:"items"`
		Total int64      `json:"total"`
	} `json:"data"`
}

// TopologyList struct
type TopologyInfo struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    struct {
		Items *Topology `json:"items"`
		Total int64     `json:"total"`
	} `json:"data"`
}

type AutoGenerated struct {
	Message string `json:"message"`
	Status  int    `json:"status"`
	Data    struct {
		Nodes []struct {
			ID       string `json:"id"`
			Size     int    `json:"size"`
			Label    string `json:"label"`
			Text     string `json:"text"`
			IsCenter bool   `json:"isCenter"`
			SiteFlag string `json:"siteFlag"`
			IsClick  bool   `json:"isClick"`
			Style    struct {
				Fill        string `json:"fill"`
				Opacity     int    `json:"opacity"`
				FillOpacity int    `json:"fillOpacity"`
				Cursor      string `json:"cursor"`
			} `json:"style,omitempty"`
			LabelCfg struct {
				Style struct {
					Fill     string `json:"fill"`
					FontSize int    `json:"fontSize"`
				} `json:"style"`
				Position string `json:"position"`
				Offset   []int  `json:"offset"`
			} `json:"labelCfg,omitempty"`
			BackgroundConfig struct {
				Fill    string `json:"fill"`
				Padding []int  `json:"padding"`
				Radius  int    `json:"radius"`
			} `json:"backgroundConfig"`
			IsFisrtNodes bool `json:"isFisrtNodes,omitempty"`
		} `json:"nodes"`
		Edges []struct {
			Source  string `json:"source"`
			Target  string `json:"target"`
			Type    string `json:"type"`
			Label   string `json:"label"`
			LineNum int    `json:"lineNum"`
		} `json:"edges"`
	} `json:"data"`
}

type Nodes struct {
	ID           string `json:"id"`
	InternalName string `json:"internal_name"`
	Label        string `json:"label"`
	Text         string `json:"text"`
	X            string `json:"x"`
	Y            string `json:"y"`
	Type         string `json:"type"`
	Img          string `json:"img"`
}
type Edges struct {
	Source  string `json:"source"`
	Target  string `json:"target"`
	Type    string `json:"type"`
	Label   string `json:"label"`
	LineNum int    `json:"lineNum"`
	Style   struct {
		LineWidth  int    `json:"lineWidth"`
		Stroke     string `json:"stroke"`
		StartArrow bool   `json:"startArrow"`
		EndArrow   bool   `json:"endArrow"`
	} `json:"style,"`
}

type Data struct {
	Nodes []Nodes `json:"nodes"`
	Edges []Edges `json:"edges"`
}
