httpport  = 8085
runmode   = prod
timeout   = 12
log_level = 6
log_path  = log/app.log
maxlines  = 1000
maxsize   = 0
maxdays   = 10
daily     = true
; database
dbtype    = mysql
dbhost    = localhost
dbuser    = zbxtable
dbpass    = zbxtablepwd123
dbname    = zbxtable
dbport    = 3306
