httpport  = 8085
runmode   = prod
timeout   = 12
appname   = zbxtable
token     = eda5de09c1b84e93b50be83b2ba09519
log_level = 6
log_path  = logs/app.log
maxlines  = 1000
maxsize   = 0
maxdays   = 10
daily     = true
; database
dbtype    = mysql
dbhost    = localhost
dbuser    = zbxtable
dbpass    = zbxtablepwd123
dbname    = zbxtable
dbport    = 3306
