; zbxtable
appname   = zbxtable
httpport  = 8085
runmode   = prod
timeout   = 12
token     = ced46eae0ffa411f8e7bbec90cc6e68d
log_level = 6
; 日志路径，留空则默认为 ./log/yyyy-MM-dd.log
log_path  = 
maxlines  = 1000
; 单个日志文件最大大小（MB），0表示不限制
maxsize   = 100
; 日志保留天数
maxdays   = 10
; 是否按天分割日志文件
daily     = true
; database
dbtype    = mysql
dbhost    = localhost
dbuser    = zbxtable
dbpass    = zbxtablepwd123
dbname    = zbxtable
dbport    = 3306
